upload_max_filesize = 10M
post_max_size = 12M
max_file_uploads = 20
memory_limit = 256M
max_execution_time = 60
max_input_time = 60

display_errors = On
display_startup_errors = On
error_reporting = E_ALL

date.timezone = Asia/Ho_Chi_Minh
default_charset = "UTF-8"
mbstring.language = Vietnamese

session.save_handler = files
session.save_path = "/var/www/html/storage/sessions"
session.gc_maxlifetime = 1440
session.cookie_httponly = 1
session.use_strict_mode = 1

opcache.enable = 1
opcache.memory_consumption = 64
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 2
opcache.validate_timestamps = 1
